version: "3.9"
services:
  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chromadb
    environment:
      - IS_PERSISTENT=TRUE
      - ALLOW_RESET=TRUE

volumes:
  chroma_data:
